name: small runtime test

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up R 
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'

    - name: Install R dependency
      run: Rscript -e "install.packages('locfit', repos='http://cran.us.r-project.org')"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install -e .

    - name: Test from running as command line script
      run: |
        python pqam_dparamhu2021/model.py "Mo25 Nb25 Hf50"
        python pqam_dparamhu2021/model.py "MoNbHf"
        python pqam_dparamhu2021/model.py "Mo33.3 Nb33.3 Hf33.3"
        
    - name: Test from running as PyQAlloy model
      run: |
        python -c "import pqam_dparamhu2021 as m;print(m.predict('Mo25 Nb25 Hf50'));print(m.predict('MoNbHf')),print(m.predict('Mo33.3 Nb33.3 Hf33.3'))"